# Basic
title: vvcooo
subtitle: Try Best
description: Welcome Here


theme: jekyll-theme-cayman

# Navigation buttons in the front page.s
nav:
    - {title: 所有文章, description: archive, url: '/archive'}
    - {title: 标签, description: tags, url: '/tags'}
    - {title: 留言, description: liuyan, url: '/liuyan'}
    - {title: 资源, description: ziyuan, url: '/ziyuan'}
    - {title: 关于我, description: about, url: '/about'}




# Pagination
gems: [jekyll-paginate]
paginate: 20
paginate_path: "page/:num/"